### ISSUE TITLE
Kriging on points rather than a grid

### ISSUE THREAD

**Issue by arogeau** [czwchenzhun/tfinterpy#1]
Hi,
Is there a way to do the kriging interpolating at specific points rather than an entire grid ? I need to estimate values across Europe, considering longitude, latitude and altitude. The 3D grid is too big (~1e10) and I would like to interpolate only at points (~3e7).

**Comment by czwchenzhun** [comment]
Of course, the first argument accepted by the interpolator's “execute“ method is a numpy array representing the points, you can see the example code, any interpolation on the grid actually computes the points on the grid before calling the execute method。
